### ISSUE TITLE
Specified path to dsi_studio ('dsi_path') does not exist.

### ISSUE THREAD

**Issue by luanraguiar** [jdwor/LQT#1]
Dear all,

I have a question about LQT. I would greatly appreciate the help, and I apologize if it is a silly question!

When I tried to run the code, the following error appears:

**"Error in create_cfg_object(pat_ids = pat_ids, lesion_paths = lesion_paths, :
  Specified path to dsi_studio ('dsi_path') does not exist."**

However, I put in my script the path where DSI Studio is located:

library(LQT)

pat_ids = "subjectAXT1.nii"
lesion_paths = list.files('C:/Users/Neuroimager/Desktop/R - Documentos/LQT_R/VERA/LESAO',
                          full.names = TRUE)
parcel_path = system.file("extdata","Schaefer_Yeo_Plus_Subcort",
                          "100Parcels7Networks.nii.gz",package="LQT")
out_path = 'C:/Users/Neuroimager/Desktop/R - Documentos/LQT_R/VERA/OUTPUT'

**dsi_path = 'C:/Users/Neuroimager/Desktop/dsi_studio_64/dsi_studio'**

cfg = create_cfg_object(pat_ids=pat_ids,
                        lesion_paths=lesion_paths,
                        parcel_path=parcel_path,
                        out_path=out_path,
                        dsi_path=dsi_path)

**Comment by jdwor** [comment]
Hi Luan!

My best guess at the moment is that you need to specify the .exe file extension. So hopefully if you run it with dsi_path = 'C:/Users/Neuroimager/Desktop/dsi_studio_64/dsi_studio.exe' it won't throw that error anymore.

Let me know if that helps! If not I can do some more digging.

Thanks,
Jordan

**Comment by luanraguiar** [comment]
Hi Jordan, 

Thank you so much for your kindness and quick response. Your guidance of adding the ".exe" worked! However, I would be grateful if you could clarify other issues. I'll put in threads to make it easier. I'm starting to learn how to use the "r", so forgive me for possible silly questions. 


1- Regarding the available atlases and other features, is there a difference between the LQT in this package in R and the one in Matlab (Griffis et al 2021)? 

2- I used the script below to run the analysis of a patient, but I had doubts about the item "pat_ids". In the "pat_ids" I added the name of the patient image "subjectAXT1.nii", is that right? 

### ###
library(LQT)
pat_ids = "subjectAXT1.nii"
lesion_paths = 'C:/Users/Neuroimager/Desktop/R - Documentos/LQT_R/VERA/LESAO/subjectAXT1.nii'
parcel_path = system.file("extdata","Schaefer_Yeo_Plus_Subcort",
                          "100Parcels7Networks.nii.gz",package="LQT")
out_path = 'C:/Users/Neuroimager/Desktop/R - Documentos/LQT_R/VERA/OUTPUT'
dsi_path = 'C:/Users/Neuroimager/Desktop/dsi_studio_64/dsi_studio.exe'
cfg = create_cfg_object(pat_ids=pat_ids,
                        lesion_paths=lesion_paths,
                        parcel_path=parcel_path,
                        out_path=out_path,
                        dsi_path=dsi_path)
### ###

3- After running the above script, this new error appeared: 
**"Error in system(paste0("! ", cfg$dsi_path, " --action=ana --source=",  : 
  '!' not found"**
Am I forgetting to add something to "create_cfg_object"? If yes, which command would it be, please! 

4- Do I need to add the "file_sufix" in creat_cfg_object(...) ? Or its lack, it is understood that the parcellations are from the study "Schaefer_1000_17"? Would it be for parcellations files only? 

5- Is there any tutorial or vignette for LQT (with examples)? I'm not sure how to use the other arguments: con_type('end') sspl_sparec_tresh(50), smooth(2)...

**Comment by luanraguiar** [comment]
Hi Jordan,

Thank you so much for your kindness and quick response. Your guidance of adding the ".exe" worked! However, I would be grateful if you could clarify other issues.I'm starting to learn how to use the "r", so forgive me for possible silly questions.


**library(LQT)

pat_id = "subjectAXT1.nii"

lesion_paths = 'C:/Users/Neuroimager/Desktop/R - Documentos/LQT_R/VERA/LESAO/subjectAXT1.nii'

parcel_path = system.file("extdata","Schaefer_Yeo_Plus_Subcort",
                          "100Parcels7Networks.nii.gz",package="LQT")

out_path = 'C:/Users/Neuroimager/Desktop/R - Documentos/LQT_R/VERA/OUTPUT'

dsi_path = 'C:/Users/Neuroimager/Desktop/dsi_studio_64/dsi_studio.exe'

cfg = create_cfg_object(pat_ids=pat_id,
                        lesion_paths=lesion_paths,
                        parcel_path=parcel_path,
                        out_path=out_path,
                        dsi_path=dsi_path)**


1- After running the above script, this new error appeared after the "get_tract_discon(cfg)" command: 


**"Error in system(paste0("! ", cfg$dsi_path, " --action=ana --source=",  : 
  '!' not found"**

Am I forgetting to add something to "create_cfg_object"? If yes, which command would it be, please!

**Comment by jdwor** [comment]
Glad to hear the .exe helped! 

I'm going to close this issue and open a new one for your follow-up question, just to keep the different errors organized in case anyone else comes across them
