### ISSUE TITLE
Misc. questions

### ISSUE THREAD

**Issue by jdwor** [jdwor/LQT#3]
From @luanraguiar

1- Regarding the available atlases and other features, is there a difference between the LQT in this package in R and the one in Matlab (Griffis et al 2021)?

2- I had doubts about the item "pat_ids". In the "pat_ids" I added the name of the patient image "subjectAXT1.nii", is that right?

3- Do I need to add the "file_sufix" in creat_cfg_object(...) ? Or its lack, it is understood that the parcellations are from the study "Schaefer_1000_17"? Would it be for parcellations files only?

4- Is there any tutorial or vignette for LQT (with examples)? I'm not sure how to use the other arguments: con_type('end') sspl_sparec_tresh(50), smooth(2)...

**Comment by jdwor** [comment]
1 - I attempted to make this package as faithful as possible to the original Matlab toolbox. I'm still working on adding additional parcellations, but the package allows you to reference your own parcellation file (in MNI space) if you'd like. And it should have all of the same functionality as the Matlab package.

2 - "pat_ids" is asking you to list the patient IDs that correspond to the lesion images. These IDs will be used as folder names and included in file names of results files. If your study's patients have known ID numbers (e.g., X032), you should provide those so you can easily link the LQT results to the rest of your study data.

3 - "file_suffix" is not required, it is just giving you the opportunity to customize the way results files are named. If you have a naming convention you'd prefer, you can provide it. Otherwise the default setting will name your results files according to your chosen parcellation.

4 - The ReadMe page of the github repository is currently the only tutorial I've created, but every function has documentation that can be accessed using the '?' in R. For example, to learn more about the arguments passed to 'create_cfg_object', you could type '?create_cfg_object'. Most of the optional settings (like con_type, sspl_sparec_thresh, or smooth) are set to reasonable default values, and don't need to be changed unless you have a prior reason to.

**Comment by luanraguiar** [comment]
Thank you very much for the reply and attention!

**Comment by jdwor** [comment]
No problem! I'm going to close this issue, but feel free to start a new one if you have additional concerns about any of these topics.
