### ISSUE TITLE
Google Collab

### ISSUE THREAD

**Issue by luanraguiar** [jdwor/LQT#4]
Hi Jordan,

How are you? I'm in touch to see if it's possible to run LQT using "Google Collab" (https://colab.research.google.com/;  or even Jupyter Notebook)? And if so, what would the path to dsi_studio look like, please.

Thank you very much !

Best,
Luan.

**Comment by jdwor** [comment]
Hi Luan,

I'm not very familiar with Google Collab or Jupyter Notebooks - so the short answer is I'm not sure. It does seem like you can run R code within Google Collab, but it's not clear whether you can draw from an external software package like dsi_studio.

At the moment, I'm still focusing on the R-specific functionality of this package, so I probably won't be able to look into this much on my end. But if you do any more digging and figure out a way to run it in these platforms feel free to let me know.

Best,
Jordan

**Comment by luanraguiar** [comment]
Hi Jordan,
I did some tests on Collab and I didn't have much success because of the DSI, but I'll study more on the topic, and if I succeed in this line or find something exciting I'll let you know.

Thank you very much for your attention and help!

Best,
Luan.
