### ISSUE TITLE
Enter a numerical threshold to binarize the masks

### ISSUE THREAD

**Issue by jdwor** [jdwor/LQT#5]
From @luanraguiar

A question that didn't appear before came up "Enter a numerical threshold to binarize the masks, or enter 'c' to cancel:" . What would be the best answer?

**Comment by jdwor** [comment]
The package currently only works with binary lesions masks (i.e., values of 0/1, or FALSE/TRUE). So if it notices that your lesion mask isn't binary, it asks you to provide a threshold for which voxels below that threshold are set to 0, and voxels above that threshold are set to 1. 

For example, if you provide a probability map where voxels have continuous values between 0 and 1, you could set the threshold to be 0.5, such that voxels with a greater than 50% probability of being lesions are set to 1, and voxels with a less than 50% probability are set to 0.

This threshold is very context-dependent, and it should be set based on your knowledge of the values in your lesion masks. Thus, there is no default threshold; it must be provided manually.

You can also turn your lesion images into binary masks before using the LQT package. Then this message will not appear.

**Comment by luanraguiar** [comment]
Hi Jordan,

Thank you very much for the explanation! I added the binary lesion mask. And checked it using the following FSL commands:   
``  fslstats lesion -M -S  ``

Best regards,
Luan
